alias gti='git'
alias gs='git status'
alias gf='git diff'
alias ga='git add'
alias gb='git branch'
alias gbl='git branch --sort=-committerdate'
alias gl='git log --oneline -n 23'
alias gla='git log --oneline'
alias gcam='git commit -am'
alias gch='git checkout '
alias gcane='git commit --amend --no-edit'
alias gitlast='git log --pretty=format: --name-only -n 1'
alias vimlast='vim -p $(gitlast)'
alias vim-gs='vim -p $(git ls-files -m)'
alias tmuxdev='tmux new -s vf \; split-window -v \; split-window -h \;'
alias renamespace='rename "s/ /_/g" *'
alias weather='curl http://v2.wttr.in/Lviv'
alias ..='cd ..'
alias 2..='cd ../..'
alias 3..='cd ../../..'
alias 4..='cd ../../../..'
alias ipy='ipython'
