alias gti='git'
alias gs='git status'
alias gf='git diff'
alias ga='git add'
alias gb='git branch'
alias gcam='git commit -am'
alias gch='git checkout '
alias gitlast='git log --pretty=format: --name-only -n 1'
alias vimlast='vim -p $(gitlast)'
alias tmuxdev='tmux new -s vf \; split-window -v \; split-window -h \;'
alias renamespace='rename "s/ /_/g" *'
